version: '3'

services:
  db:
    image: kartoza/postgis
    environment:
      - POSTGRES_USER=chikitshak
      - POSTGRES_PASSWORD=chikitshak
      - POSTGRES_DB=chikitshak
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/chikitshak
    ports:
      - "9000:9000"
    command: bash -c "uwsgi --ini uwsgi.ini --http :9000"
    depends_on:
      - db
    restart: always
  server:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/srv/chikitshak/static
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/chikitshaknginx.conf:/etc/nginx/sites-enabled
    restart: always
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgresql-data:
  redis-data:
